version: '3'
services:
  proxy:
    image: osminogin/tor-simple
    ports:
      - 9050:9050
    networks:
      - mynet

  crawler:
    build: .
    depends_on:
      - proxy
    networks:
      - mynet

networks:
  mynet:
