version: '3'
services:
  proxy:
    build:
      context: ./tor

  crawler:
    build: .
    environment:
      - http_proxy=http://proxy:9050
      - https_proxy=http://proxy:9050
      - PYTHONUNBUFFERED=0

    links:
      - tor

networks:
  mynet:
